<script>
export default {
  name: 'data',
  data: [
    {
      module: 'A',
      parts: [
        {
          part_no: 3211612030,
          part_name: 'SPACER, DRIVE PLATE, FR ',
          unique_no: 'T107',
          qty_kanban: 4,
          qty_remain: 2,
          address: 2,
        },
        {
          part_no: 9010510095,
          part_name: 'BOLT, WASHER BASED HEAD HEXAGON ',
          unique_no: 'T116',
          qty_kanban: 2,
          qty_remain: 1,
          address: 6,
        },
        {
          part_no: 9012608063,
          part_name: 'STUD, HEXALOBULAR ',
          unique_no: 'T118',
          qty_kanban: 5,
          qty_remain: 2,
          address: 6,
        },
        {
          part_no: 9020110344,
          part_name: 'WASHER, PLATE ',
          unique_no: 'T121',
          qty_kanban: 5,
          qty_remain: 3,
          address: 6,
        },
      ],
    },
    {
      module: 'A1',
      parts: [
        {
          part_no: 3211612030,
          part_name: 'SPACER, DRIVE PLATE, FR ',
          unique_no: 'T107',
          qty_kanban: 4,
          qty_remain: 2,
          address: 2,
        },
        {
          part_no: 9010510095,
          part_name: 'BOLT, WASHER BASED HEAD HEXAGON ',
          unique_no: 'T116',
          qty_kanban: 2,
          qty_remain: 1,
          address: 6,
        },
        {
          part_no: 9012608063,
          part_name: 'STUD, HEXALOBULAR ',
          unique_no: 'T118',
          qty_kanban: 5,
          qty_remain: 2,
          address: 6,
        },
        {
          part_no: 9020110344,
          part_name: 'WASHER, PLATE ',
          unique_no: 'T121',
          qty_kanban: 5,
          qty_remain: 3,
          address: 6,
        },
      ],
    },
    {
      module: 'B',
      parts: [
        {
          part_no: 3211612030,
          part_name: 'SPACER, DRIVE PLATE, FR ',
          unique_no: 'T107',
          qty_kanban: 4,
          qty_remain: 2,
          address: 2,
        },
        {
          part_no: 9010510095,
          part_name: 'BOLT, WASHER BASED HEAD HEXAGON ',
          unique_no: 'T116',
          qty_kanban: 2,
          qty_remain: 1,
          address: 6,
        },
        {
          part_no: 9012608063,
          part_name: 'STUD, HEXALOBULAR ',
          unique_no: 'T118',
          qty_kanban: 5,
          qty_remain: 2,
          address: 6,
        },
      ],
    },
    {
      module: 'AB',
      parts: [
        {
          part_no: 3211612030,
          part_name: 'SPACER, DRIVE PLATE, FR ',
          unique_no: 'T107',
          qty_kanban: 4,
          qty_remain: 2,
          address: 2,
        },
        {
          part_no: 9010510095,
          part_name: 'BOLT, WASHER BASED HEAD HEXAGON ',
          unique_no: 'T116',
          qty_kanban: 2,
          qty_remain: 1,
          address: 6,
        },
      ],
    },
    {
      module: 'B1',
      parts: [
        {
          part_no: 3211612030,
          part_name: 'SPACER, DRIVE PLATE, FR ',
          unique_no: 'T107',
          qty_kanban: 4,
          qty_remain: 2,
          address: 2,
        },
      ],
    },
    {
      module: 'C',
      parts: [],
    },
    {
      module: 'D',
      parts: [],
    },
    {
      module: 'F1',
      parts: [],
    },

    {
      module: 'R',
      parts: [
        {
          part_no: 3211612030,
          part_name: 'SPACER, DRIVE PLATE, FR ',
          unique_no: 'T107',
          qty_kanban: 4,
          qty_remain: 2,
          address: 2,
        },
        {
          part_no: 9010510095,
          part_name: 'BOLT, WASHER BASED HEAD HEXAGON ',
          unique_no: 'T116',
          qty_kanban: 2,
          qty_remain: 1,
          address: 6,
        },
        {
          part_no: 9012608063,
          part_name: 'STUD, HEXALOBULAR ',
          unique_no: 'T118',
          qty_kanban: 5,
          qty_remain: 2,
          address: 6,
        },
        {
          part_no: 9020110344,
          part_name: 'WASHER, PLATE ',
          unique_no: 'T121',
          qty_kanban: 5,
          qty_remain: 3,
          address: 6,
        },
      ],
    },
    {
      module: 'U1',
      parts: [
        {
          part_no: 3211612030,
          part_name: 'SPACER, DRIVE PLATE, FR ',
          unique_no: 'T107',
          qty_kanban: 4,
          qty_remain: 2,
          address: 2,
        },
        {
          part_no: 9010510095,
          part_name: 'BOLT, WASHER BASED HEAD HEXAGON ',
          unique_no: 'T116',
          qty_kanban: 2,
          qty_remain: 1,
          address: 6,
        },
        {
          part_no: 9012608063,
          part_name: 'STUD, HEXALOBULAR ',
          unique_no: 'T118',
          qty_kanban: 5,
          qty_remain: 2,
          address: 6,
        },
        {
          part_no: 9020110344,
          part_name: 'WASHER, PLATE ',
          unique_no: 'T121',
          qty_kanban: 5,
          qty_remain: 3,
          address: 6,
        },
      ],
    },
    {
      module: 'S1',
      parts: [
        {
          part_no: 3211612030,
          part_name: 'SPACER, DRIVE PLATE, FR ',
          unique_no: 'T107',
          qty_kanban: 4,
          qty_remain: 2,
          address: 2,
        },
        {
          part_no: 9010510095,
          part_name: 'BOLT, WASHER BASED HEAD HEXAGON ',
          unique_no: 'T116',
          qty_kanban: 2,
          qty_remain: 1,
          address: 6,
        },
        {
          part_no: 9012608063,
          part_name: 'STUD, HEXALOBULAR ',
          unique_no: 'T118',
          qty_kanban: 5,
          qty_remain: 2,
          address: 6,
        },
      ],
    },

    {
      module: 'T',
      parts: [
        {
          part_no: 3211612030,
          part_name: 'SPACER, DRIVE PLATE, FR ',
          unique_no: 'T107',
          qty_kanban: 4,
          qty_remain: 2,
          address: 2,
        },
        {
          part_no: 9010510095,
          part_name: 'BOLT, WASHER BASED HEAD HEXAGON ',
          unique_no: 'T116',
          qty_kanban: 2,
          qty_remain: 1,
          address: 6,
        },
        {
          part_no: 9012608063,
          part_name: 'STUD, HEXALOBULAR ',
          unique_no: 'T118',
          qty_kanban: 5,
          qty_remain: 2,
          address: 6,
        },
        {
          part_no: 9020110344,
          part_name: 'WASHER, PLATE ',
          unique_no: 'T121',
          qty_kanban: 5,
          qty_remain: 3,
          address: 6,
        },
      ],
    },
    {
      module: 'S',
      parts: [
        {
          part_no: 3211612030,
          part_name: 'SPACER, DRIVE PLATE, FR ',
          unique_no: 'T107',
          qty_kanban: 4,
          qty_remain: 2,
          address: 2,
        },
        {
          part_no: 9010510095,
          part_name: 'BOLT, WASHER BASED HEAD HEXAGON ',
          unique_no: 'T116',
          qty_kanban: 2,
          qty_remain: 1,
          address: 6,
        },
        {
          part_no: 9012608063,
          part_name: 'STUD, HEXALOBULAR ',
          unique_no: 'T118',
          qty_kanban: 5,
          qty_remain: 2,
          address: 6,
        },
        {
          part_no: 9020110344,
          part_name: 'WASHER, PLATE ',
          unique_no: 'T121',
          qty_kanban: 5,
          qty_remain: 3,
          address: 6,
        },
      ],
    },
    {
      module: 'Z',
      parts: [
        {
          part_no: 3211612030,
          part_name: 'SPACER, DRIVE PLATE, FR ',
          unique_no: 'T107',
          qty_kanban: 4,
          qty_remain: 2,
          address: 2,
        },
        {
          part_no: 9010510095,
          part_name: 'BOLT, WASHER BASED HEAD HEXAGON ',
          unique_no: 'T116',
          qty_kanban: 2,
          qty_remain: 1,
          address: 6,
        },
        {
          part_no: 9012608063,
          part_name: 'STUD, HEXALOBULAR ',
          unique_no: 'T118',
          qty_kanban: 5,
          qty_remain: 2,
          address: 6,
        },
      ],
    },
  ],
}
</script>
